#----------------------------------------------------------------------
#memo:入力は進む距離と進行速度
#memo: サービスに対して要求があったら resultとdistance,velocityを返す。
#----------------------------------------------------------------------

#request
#型 フィールド名
float32 distance
float32 velocity
---
#response
bool result


